### ISSUE TITLE
Webpack with SAM?

### ISSUE THREAD

**Issue by azarboon** [awslabs/serverless-application-model#1007]
Hi. Is there any way to use SAM with webpack? If not, can you provide this possibility?
Somewhere, I saw something for Typecript, but I need for JavaScript.

**Comment by buggy** [comment]
It's definitely possible. I wrote a blog post about [building SAM with Webpack for TypeScript](http://www.goingserverless.com/blog/building-apps-with-sam-typescript-and-vscode-debugging). The webpack config supports both TypeScript and Babel (for JavaScript). You just need to modify the `webpack` script inside the `package.json` so it builds `src/index.js` instead of `src/index.ts`.

There's also an issue for [adding a Webpack builder to SAM](https://github.com/awslabs/aws-lambda-builders/issues/116). I've been trialing some updates to the blog post I wrote that will hopefully go into this.

**Comment by brettstack** [comment]
I recently added an example here https://github.com/awslabs/aws-serverless-express/tree/v4/examples/lambda-edge which uses Webpack to bundle a Lambda Function. If you're asking for SAM CLI support, please open an issue in that repo https://github.com/awslabs/aws-sam-cli.

**Comment by trivikr** [comment]
Issue was created with AWS SAM CLI at https://github.com/awslabs/aws-sam-cli/issues/1277
