### ISSUE TITLE
Mixing SAM and normal CF API Gateway causes methods to be lost

### ISSUE THREAD

**Issue by jasonmk** [awslabs/serverless-application-model#1040]
**Description:**

I'm not actually certain whether this is a SAM issue or a CloudFormation issue, but figured I'd report it here just in case.

If a SAM template has Serverless Functions with API Events as well as SAM Functions attached to an API using normal CF resources, then making changes to the SAM-configured functions causes the CF configured ones to disappear.

Since that's a fairly obtuse description, it will become more obvious looking at the attached template: 
[houdini.yaml.txt](https://github.com/awslabs/serverless-application-model/files/3432495/houdini.yaml.txt)

**Steps to reproduce the issue:**
1. Generate a new empty SAM project
2. Replace template.yaml with attached houdini.yaml
3. Deploy stack using SAM (notice that API has 2 resources: hello and goodbye)
4. Uncomment function 'fubar'
5. Update stack using SAM

**Observed result:**

The goodbye resource has disappeared and only hello and fubar are present.

**Expected result:**

All three resources should exist.

**Comment by jasonmk** [comment]
As near as I can tell, it works the first time because SAM calculates the entire API that it knows about and adds it as a CF resource.  CF then sees the additional resources and adds them.

On an update, SAM again calculates the entire API that it knows about, sees that there has been a change and submits it as an update which unfortunately replaces the entire existing API.  However since the other resources haven't changed, CF sees no reason to do anything with them.

**Comment by jasonmk** [comment]
One additional piece of information.  If you make a change (for example the path) of the goodbye function at the same time you add the fubar function, then the resulting API has all three functions, so it definitely seems to be a case of the entire API gateway being replaced.

**Comment by jlhood** [comment]
@jasonmk What you're experiencing has to do with the fact that there are 2 ways to configure an API Gateway REST API in CloudFormation: (1) Defining the API as a swagger document on the `AWS::ApiGateway::RestApi` resource and (2) Defining the API using resource types like `AWS::ApiGateway::Resource` and `AWS::ApiGateway::Method`. The two ways are not compatible with one another so you have to choose one way (swagger) or the other (explicit API Gateway resource types).

When you use SAM, SAM chooses option 1 in the background, so the behavior you're experiencing is because you are declaring the goodbye API endpoint via option 2 which works initially, but then on subsequent deployments, the swagger generated by SAM overrides the resources you're manually defining in CloudFormation.
