### ISSUE TITLE
Feature Request: Add Name for AWS::Serverless::Api

### ISSUE THREAD

**Issue by digitalfiz** [awslabs/serverless-application-model#113]
This is available if you use `AWS::ApiGateway::RestApi` but not when using `AWS::Serverless::Api`

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html

**Comment by digitalfiz** [comment]
You can effectively set the name of the api in the `DefinitionBody`inline swagger by setting `info.title`. I assume you can do the same in the `DefinitionUri` swagger. Haven't tried it though.

I don't think that solves this issue but I thought I would add it here incase anyone else is wanting to solve this problem and this can be an option.

**Comment by rue-stephen** [comment]
👍 for feature request

i tried setting a stage variable in the serverless api definition to be substituted in the swagger title. just like the api-swagger-cors example in this repo. that didn't work either.

this is quite an annoying, because all (possibly many) instances of an api from the same swagger file have the exactly the same name in the api gateway console. leading to confusion and risk of messing with the wrong one.

**Comment by sanathkr** [comment]
`Name` support has been added to SAM. I will update the documentation tomorrow. Can you verify?

**Comment by Dunedan** [comment]
Works like a charm. :+1:
