### ISSUE TITLE
Missing cloudwatch:DescribeAlarmHistory in serverless function Policy List

### ISSUE THREAD

**Issue by zmaleki** [awslabs/serverless-application-model#1265]
**Description:**
We have a lambda that requires cloudwatch:DescribeAlarmHistory and we want to use sam template for our lambda. However, DescribeAlarmHistory is not one of the available policies.

**Steps to reproduce the issue:**
Pull request https://github.com/awslabs/serverless-application-model/pull/1264

**Comment by chrisoverzero** [comment]
Is there a reason that your application requires such a specific SAM Policy Template instead of using an [IAM Policy object][]? Arbitrary policies can be assigned to Functions, as you can see in [some of the example applications][]. 

[IAM Policy object]: http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies.html
[some of the example applications]: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/cloudwatch-event-to-msteams/template.yaml
