### ISSUE TITLE
Issues with type on sam translator

### ISSUE THREAD

**Issue by kddejong** [awslabs/serverless-application-model#1410]
https://github.com/awslabs/serverless-application-model/blob/5be0b07efb5265671e6e9848b2397918673520b5/samtranslator/translator/translator.py#L55

Would it be possible to switch this line to `if isinstance(rest_api, (dict, OrderedDict)):`?

**Comment by jlhood** [comment]
@kddejong Put up a PR with the suggested change. The rest of the team will doublecheck me, but since all tests pass, I think the change should be fine. Note, I didn't search the code for other occurrences of using `type()` so not sure I completely fixed the problem. Just trying to get you fast turnaround on this specific ask.

**Comment by ShreyaGangishetty** [comment]
This is released in [v1.22.0](https://github.com/awslabs/serverless-application-model/releases/tag/v1.22.0)
