### ISSUE TITLE
Define an API in Swagger, integrations in CloudFormation

### ISSUE THREAD

**Issue by cjkent** [awslabs/serverless-application-model#166]
I'd like to be able to:

* Define an API using plain Swagger with no AWS extensions
* Map API endpoints to Lambda functions using `Event` entries in the CloudFormation file

The reason we use Swagger is so we can share an API definition with the consumers of the API. We don't want to share a Swagger file that includes provider-specific extensions containing implementation details of the API. This defeats the point of having neutral format for defining an API.

This relates to #5

**Comment by sanathkr** [comment]
This is an interesting idea. With how we are planning on supporting CORS in #248 I think this will come for free. When customers want to use CORS with their own Swagger file, we have to inject cors definitions into their swagger. We might be able to do extend the infrastructure to inject Events as well. 

I am not committing to this, but i will keep the issue open for future reference.

**Comment by lafiosca** [comment]
I sort of worked around this from the other direction. We use a Swagger spec with the Amazon extensions for our deployment, and then we run a command to pull the "clean" Swagger spec back from API Gateway:

```
#!/bin/bash

ApiStack=MyApiStack
ApiStageName=Api
SwaggerFile=api-swagger.json

ApiId=`aws cloudformation describe-stacks --stack-name $ApiStack | jq -r '.Stacks[0].Outputs[] | select(.OutputKey == "ApiId") | .OutputValue'`

aws apigateway get-export --rest-api-id ${ApiId} --stage-name ${ApiStageName} --export-type swagger ${SwaggerFile}
```

(Note that this requires your API stack to have ApiId, referencing the AWS::Serverless::Api resource, as one of its outputs.)

**Comment by keetonian** [comment]
I do not think that we can support this model on the existing `AWS::Serverless::Api` resource, since it would alter a lot of existing OpenApi/Swagger documents.

However, in the new `AWS::Serverless::HttpApi` and corresponding `HttpApi` event, we followed this model, where if an APIGW extension does not exist but SAM expects it to exist from the template configuration, SAM will add this extension into the template, along with any missing methods/paths/etc.

For more information about the new `AWS::Serverless::HttpApi` resource, see the release notes from the recent release: https://github.com/awslabs/serverless-application-model/releases/tag/v1.19.0
