### ISSUE TITLE
Help needed with CodeUri

### ISSUE THREAD

**Issue by flameoftheforest** [awslabs/serverless-application-model#196]
Hi,
I refer to the example `https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/s3_processor/template.yaml`

I cannot see how the `<bucket>` in `line 10` and how is it associated to a `Bucket` resource in `line 19`.

I would like to know how is `<bucket>` associated to a `Bucket` resource please.

Also, I am also at a loss why we should associate `CodeUri` to a bucket when we are specifying `--s3-bucket`  in the `aws cloudformation package`. The document seems to have left out the rationale.

Please help.

Thank you.

Bryan

**Comment by seeebiii** [comment]
Hi Brian,

regarding your first question: `<bucket>` in line 10 can be related to `Bucket` in line 19, but must not. What you define in line 10 is where your code artifact for your Lambda function can be picked up by `aws cloudformation package` (see also my answer to your second question below). The `Bucket` in line 19 defines a bucket which is able to call your Lambda function if a new object is created in that bucket.

Regarding your second question: you use `CodeUri` to define where you're artifacts are at the moment and where the AWS cli can pick them up when calling `aws cloudformation package`. `--s3-bucket` is then used for those artifacts which are e.g. on your local machine, so they are uploaded to S3 and can be referenced (because AWS has no access to your local machine obviously).

I hope I could help you with this.

Cheers,
Sebastian

**Comment by jfuss** [comment]
@seeebiii answered the question well here. There hasn't been a follow up question so closing.

**Comment by mk2130** [comment]
hi @seeebiii  I am using codepipeline which pull code from git and store it to s3 ,after successful build and calling aws cloudformation package command my template contain same CodeUri path as present in my first template.yml file,can you please help me with this ,that which CodeUri should I mention then it will get converted to build code path.
