### ISSUE TITLE
ERROR: None of the Serverless functions in your SAM template were able to be mounted. See above for errors.

### ISSUE THREAD

**Issue by gitowiec** [awslabs/serverless-application-model#205]
I wanted to try this example https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/hello_world but all I got is an error as in the subject.

I copied both files to my linux laptop, run `sam local start-api`, Docker initialized download, download finished and this error showed up:

```
2017/10/06 13:44:34 Connected to Docker 1.32
2017/10/06 13:44:34 Fetching lambci/lambda:nodejs6.10 image for nodejs6.10 runtime...
nodejs6.10: Pulling from lambci/lambda
Digest: sha256:7eb4ced6a15ae3c30effc4ec0cd3aabb2bd57c9a8330b37920c3d5d722d81083
Status: Image is up to date for lambci/lambda:nodejs6.10
2017/10/06 13:44:36 Ignoring HelloWorldFunction (index.handler) as no API event sources are defined
ERROR: None of the Serverless functions in your SAM template were able to be mounted. See above for errors.
```

**Comment by seeebiii** [comment]
Well, the hello world example can not work with `sam local start-api` because it does not define any API to access the Lambda. If you read the error message carefully, you will notice that the message `no API event sources are defined` gives you everything you need: the hello world example which you've referenced has no `Events` defined. You could expand your hello world Lambda definition like this:

```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```

Then run `sam local start-api` in your code directory and you should be able to access your Lambda function in your browser with `http://localhost:3000/hello`.

_Disclaimer: I had to remove the `CodeUri` part of the hello world template, because it was failing with `sam local`._

**Comment by jfuss** [comment]
@gitowiec Did the above explanation by @seeebiii answer your question?

**Comment by jfuss** [comment]
Closing since there has been no response.
