### ISSUE TITLE
Add support for "Body" param in AWS::Serverless::Api

### ISSUE THREAD

**Issue by jamesls** [awslabs/serverless-application-model#21]
If you want to leverage additional capabilities of API gateway (i.e CORS support, mock requests, etc) you'll need to create a swagger doc.  The only option right now is to create a swagger file, upload it to S3, and reference it via the `DefinitionUri` template.

As #8 alludes to, if you want to share data, you'll have to coordinate the `variables` section in `AWS::Serverless::Api` with the `${stageVariables.<foo>}` in the swagger file.

It would be really helpful to support the `Body` param from http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html.

Benefits:

1. Can leverage all the cloudformation functions within the swagger body.
2. Simplifies process for tools wanting to generate SAM templates.  Everything (except the lambda deployment package) can be in a single file vs. generating a swagger file, uploading to s3, generating a SAM template that references the swagger file.

**Comment by djamison** [comment]
@jamesls You should check out `aws cloudformation package`, which automates the process of uploading your swagger definition file and generates a cloudformation file that references that uploaded file. AWS has a [tutorial](http://docs.aws.amazon.com/lambda/latest/dg/serverless-deploy-wt.html). (Maybe that's what you meant? That process seems pretty simple to me.)

I found myself dropping the SAM Api in favor of `AWS::ApiGateway::RestApi` (which meant adding Stage/Deployment too) so I could include the full swagger body in the CF template. Now I'm able to avoid the `stageVariables` altogether because I can grab the ARN of the lambda functions in places like `x-amazon-apigateway-authorizer`. In my `AWS::Serverless::Function` Events, I just point to the RestApi instead of the SAM Api and that seems to work.

NB: `aws cloudformation package` will break the `AWS::ApiGateway::RestApi` because it adds a `BodyS3Location` reference while leaving the `Body` in place, which is invalid CF. You need to pick one. I just delete the `BodyS3Location`.

**Comment by jamesandersen** [comment]
FYI, this issue of the `BodyS3Location` being generated in the output file when only using an inline `Body` appears to have been addressed here: aws/aws-cli#2320

**Comment by sanathkr** [comment]
`DefinitionBody` is here! - https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapi

**Comment by balldarrens** [comment]
@djamison - might you be able to post an example of using AWS::ApiGateway::RestApi instead of the SAM Api?

**Comment by ffxsam** [comment]
@sanathkr Could you provide some sort of example on how to use this? I tried the following but it doesn't seem to work:

```yaml
      DefinitionBody: |
        swagger: 2.0
        info:
          title: SomeTitle
        paths:
          "/graphql":
          ...
```

Also, is it possible within the `DefinitionBody` to use CloudFormation functions like `!Ref`?
