### ISSUE TITLE
Api - DefinitionUri - Bucket in a different region

### ISSUE THREAD

**Issue by ba-alex** [awslabs/serverless-application-model#216]
Hello,

If I try to deploy a stack with a s3 bucket in another region than the one in which I deploy the stack then I get this error:
"The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."

I guess the limitation is in the URI style s3://bucket/key in which we can't precise the region endpoint.

**Comment by jfuss** [comment]
Can you provide the relevant snip-it of what you are trying to deploy.

I can't seem to find the documentation for it (found [this](https://forums.aws.amazon.com/thread.jspa?threadID=229092) forum post though) but the S3 bucket will need to be in the same region as the Lambda Function.

**Comment by ba-alex** [comment]
It's not about the codeUri attribute for a lambda function (because as you stated, it's an AWS limitation, the bucket has to be in the same region as the function) but the DefinitionUri which aim to a S3 location containing the Swagger document for an API.
I've fixed this by using the solution provided by dinvlad here: https://github.com/awslabs/serverless-application-model/issues/8#issuecomment-290212883
It fixed my bucket location problem and allowed me to use the Fn::Sub in my Swagger file for the function arn.

However, I think it's still an issue not be able to have the Swagger file in a different region than the one in which we deploy the stack?

**Comment by jfuss** [comment]
Why should swagger be any different and have a different limitation than your Lambda function code? They are both stored in S3. To my knowledge, this is expected behavior.

I don't have a ton of context on why this was done this way. I think this is done for some kind of safety and reduce blast radius, but let me talk with some folks and get back to you. 

From digging through some of the SAM code, we don't look to be doing any validation on the bucket in terms of what region it is in. So CloudFormation must be complaining. This would mean that AWS::Gateway::RestApi CloudFormation resource is not allowing cross-region, not AWS::Serverless::Api. 

Have you looked into [S3 cross-region replication](http://docs.aws.amazon.com/AmazonS3/latest/dev/crr.html)? Wouldn't this give you what you want but still allow the content of the bucket be in the other regions you need?

**Comment by ba-alex** [comment]
Hello,

Sorry for late answer.
It's just I can't find documentation on AWS stipulating the Swagger definition must in the same region as the API Gateway.
But as you said, it's a limitation from AWS::Gateway::RestApi Cloudformation resource.

Thank you!
Alexandre
