### ISSUE TITLE
'AutoPublishAlias: live' - how to deploy and test function before it goes live?

### ISSUE THREAD

**Issue by quarryman** [awslabs/serverless-application-model#239]
Hi there.
'AutoPublishAlias: live' docs say:

> In production, you will first update your function code, publish a new version, invoke the version directly to run tests against it, and after you are satisfied flip the Alias to point to the new version

How to achieve this actually if 'AutoPublishAlias: live' publishes new version and updates alias to point to it immediately?

How I can publish new Lambda version with aliases still pointing to stable version with SAM?

**Comment by Nr18** [comment]
You need to use the `DeploymentPreference ` see: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#deploymentpreference-object

You can then invoke a lambda function that performs the integration tests using the PreTraffic once the test are done you need to signal CodeDeploy so that it can route traffic to the new version.

**Comment by quarryman** [comment]
Thanx for the idea, it's 99% clear now.

If I define PreHook Lambda handler, no traffic will be sent to my function, until I do explicit call to CodeDeploy with 'success'. 
Do I get it right that once called, PreHook lambda 'callback()' function call is not what will identify success or failure? 
Lambda can respond with callback() immediately (no matter what that response is) and I can later send notification to CodeDeploy using identifier that is passed to lambda.
Or I have to somehow respond using callback() function passed to lambda?

**Comment by Nr18** [comment]
As far as i know (no experience yet) you can use the lambda to trigger whatever you want (step functions, etc) and traffic is not send to the new version until you send a success to CodeDeploy.

Having said that the CloudFormation template does have a timeout if it takes to long to deploy your template, see: http://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html

> --timeout-in-minutes (integer)
> The amount of time that can pass before the stack status becomes CREATE_FAILED; if disable-rollback is not set or is set to false , the stack will be rolled back.

That option does not exist in the `deploy` or `update-stack` as far as i can see.

**Comment by quarryman** [comment]
@Nr18 thanx for clarification.
Still I didnt manage to find documentation how to send 'a success to CodeDeploy'. Can someone give me the reference to particular API call I must use to notify COdeDeploy of success/failure?

**Comment by jfuss** [comment]
You can find some more detailed information reading this issue:  https://github.com/awslabs/serverless-application-model/issues/219

We have a couple updates to docs we need to do but haven't had the chance to get to due to the holidays.

The API is put_lifecycle_event_hook_execution_status' on the CodeDeploy client.
You can follow this example: http://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#reference-appspec-file-structure-hooks-section-structure-lambda-sample-function

Also make sure the lambda hook function name is CodeDeployHook_*

Sent from my iPhone

On Dec 26, 2017, at 9:19 AM, Alexey Bratushka <notifications@github.com<mailto:notifications@github.com>> wrote:


@Nr18<https://github.com/nr18> thanx for clarification.
Still I didnt manage to find documentation how to send 'a success to CodeDeploy'. Can someone give me the reference to particular API call I must use to notify COdeDeploy of success/failure?

-

**Comment by sanathkr** [comment]
This PR is adding a lot of the missing documentation - https://github.com/awslabs/serverless-application-model/pull/246. It should be merged shortly.

**Comment by sanathkr** [comment]
Closing this since the question is answered in the PR. Feel free to re-open if you have more questions
