### ISSUE TITLE
Allow Naming IoTRule Event for better management or point to existing rule

### ISSUE THREAD

**Issue by bpair** [awslabs/serverless-application-model#241]
Currently the IoTRule Event is generated with a very long name that is not intuitive:
Something like:  awscodestar<projectname>lambda<functionname>IoT<longuniquebuildid>

I am guessing at what the name means. It would be really nice if the rule name could be defined so that the function alias could be part of the IoTRule name. 

Also I am hoping we could just point to an existing rule so that one rule can trigger more than one action.  

This way if my build could not be cleaned up I would have a better chance of deleting rules manually or at least organizing the rules.

**Comment by sanathkr** [comment]
So you want to be able to explicitly set [RuleName](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-topicrule.html#cfn-iot-topicrule-rulename) property? 

Pointing to an existing rule would be harder because CloudFormation does not provide the ability to modify existing resources. But we could certainly add RuleName property, if that makes sense
