### ISSUE TITLE
RestApi DefinitionBody is not working anymore 

### ISSUE THREAD

**Issue by manojItela** [awslabs/serverless-application-model#346]
I am using SAM Cloud formation template to provision my serverless backend. I was using [this](https://drive.google.com/file/d/1XqB1F1iEYSgKvxlsS5fj0L6BVpq9qs1N/view?usp=sharing) template. It consists of a Lamda Function and a RestAPi. Earlier, all the resource endpoints, authorizers, and binary media types I have mentioned inside the DefinitionBody used to get applied and it was working without any issue. But recently (from last week) anything I specify inside the DefinitionBody is not getting applied. The only endpoint that is getting created is the {proxy+} endpoint since it is specified inside Lamda Function's events section. I am wondering what has happened all of a sudden. Can somebody guide me on this, please? 

Cloud Formation Template URL : https://drive.google.com/file/d/1XqB1F1iEYSgKvxlsS5fj0L6BVpq9qs1N/view?usp=sharing

**Comment by jfuss** [comment]
@manojItela The reason for this is because you are naming your `AWS::Serverless::Api` the same as the SAM generated one ([ServerlessRestApi](https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api))

We are working on reversing the behavior we added, since this did break for people and we do not have good documentation around not using our generated Resource's Logical Id. In the future, you should avoid naming conflicts with SAM to ensure things like this do not happen. 

One work around that I know of (other than to wait for us to deploy the patch), is to change the name of the logical id of your `AWS::Serverless::Api` and update any references. **IMPORTANT!! DO NOTE** this will **create** new resources!!! There may be others but nothing is directly coming to mind at the moment.

**Comment by manojItela** [comment]
@jfuss - I changed the logical id of the RestApi and it works like a charm. Thanks a lot.

**Comment by jfuss** [comment]
@manojItela Since you have recently gone through this, would you mind adding some details to our FAQ docs ([below here](https://github.com/awslabs/serverless-application-model/blob/develop/docs/faq.rst#how-to-deploy-lambda-edge-functions-with-sam)). 

Going to leave this open until we can get the FAQ section added.
