### ISSUE TITLE
Allow SESCrudPolicy helper to specify custom AWS region

### ISSUE THREAD

**Issue by 0xdevalias** [awslabs/serverless-application-model#513]
Currently the `SESCrudPolicy` has no way to specify the AWS region to use, and defaults to `${AWS::Region}`:
* https://github.com/awslabs/serverless-application-model/blob/develop/docs/policy_templates_data/policy_templates.json#L607

When running lambda in `ap-southeast-2`, we need to be able to point to somewhere that SES is available (eg. `us-east-1`)

I was thinking it might be possible to work around it with `Fn::Sub`, but if so.. not sure how to do it.

**Comment by jlhood** [comment]
@0xdevalias Thanks for raising this issue. For security, we try to limit policy templates to the current account/region. However, in the case of SES, you're right that it makes sense to allow for the region to be parameterized. For backwards-compatibility, we can't add a new required parameter to the existing SESCrudPolicy policy template. However, you could raise a PR that adds a new policy template that would be very similar to the [existing template](https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json#L670-L700) but parameterizing the region rather than using `AWS::Region`.

**Comment by 0xdevalias** [comment]
Not something i’ll have capacity to open a PR Ford I moved off SAM in favour of CDK a long time ago. Too rigid, too many inconsistencies, and too slow turnaround time.

**Comment by jlhood** [comment]
@0xdevalias Ah sorry, this came up in my search, but didn't see the date of the original issue. Thanks for letting me know!
