### ISSUE TITLE
Cleanup S3

### ISSUE THREAD

**Issue by Amri91** [awslabs/serverless-application-model#557]
**Description:**
As you continue to change and upload your lambda function, your S3 will fill up with useless objects.

**Steps to reproduce the issue:**
1. Use this [example](https://github.com/awslabs/serverless-application-model/tree/master/examples/apps/hello-world)
2. Run aws cloudformation package ...
3. Edit index.js
4. Run aws cloudformation package ... again

**Observed result:**
Two different files uploaded

**Expected result:**
Eventually, only a single file.

**The current workaround I've tried**
I've enabled S3 versioning and added a lifecycle rule to expire old versions, I also upload the code manually using the same name and get the latest version before I update the stack. It works but it requires extra work.

**Comment by jlhood** [comment]
aws cloudformation package writes different S3 files to the supplied S3 bucket. You're correct that it's up to the user to manage their bucket objects after they are created by the package command. I also setup a bucket lifecycle on my package buckets to auto-expire objects after a certain amount of time. Since creating the S3 bucket is outside of the SAM tooling, I don't think there's anything actionable we can do about this issue. You can open an issue on the [SAM CLI GH repo](https://github.com/awslabs/aws-sam-cli) asking for a command that will setup the S3 bucket for you.

Closing this issue as there isn't anything actionable we can do in this repo for this.
