### ISSUE TITLE
Read Access is not granted for Created Bucket in serverless-application-model/examples/apps/s3-get-object/

### ISSUE THREAD

**Issue by Kitemaker** [awslabs/serverless-application-model#618]
**Description:**
For example 'serverless-application-model/examples/apps/s3-get-object/' 
The function is triggered based on S3 Object created event , This bucket (Bucket1) is created when application is deployed. But this will not provide the S3ReadPolicy for created bucket. What is the use
of BucketNameParmaeter because that bucket is different from the bucket which trigger the code
so when function is triggered error is thrown by the function execution line No 20 :
 s3.getObject(params, (err, data)

message: 'Access Denied',
code: 'AccessDenied',
region: null,
time: 2018-10-08T04:04:12.303Z,
requestId: 'B15CFBD5901EF5CE',
extendedRequestId: 'uU0QnzdIK9AXNmKKiZQ3CuygALr1AQ7fhXVzRp8cIPcJUqbKtaFtoXLIKOkeGV3PV58NS3OoEVI=',
cfId: undefined,
statusCode: 403,
retryable: false,
retryDelay: 32.57900153367472 }

**Steps to reproduce the issue:**
1.Deploy Application
2. Find the bucket created by the application after deployment from Cloud FormationStack Detail
3. Upload a file in the bucket. Event is triggered but s3.getObject() call throws error as access is denied.

**Observed result:**
3.getObject() call throws error as access is denied.

**Expected result:**
Function should have Read Access for the Bucket created by the applicaiton

**Comment by keetonian** [comment]
Thank you for posting this! This is indeed a bug in these examples. Instead of having a Parameter called `BucketNameParameter` and referencing this parameter in the function policy, the function policy should reference the bucket that is created in the SAM template (`!Ref Bucket1`).

This fix should be applied to:
https://github.com/awslabs/serverless-application-model/blob/master/examples/apps/s3-get-object-python/template.yaml
https://github.com/awslabs/serverless-application-model/blob/master/examples/apps/s3-get-object-python3/template.yaml
https://github.com/awslabs/serverless-application-model/blob/master/examples/apps/s3-get-object/template.yaml

**Comment by tryantwit** [comment]
To add to this issue the same pattern also appears in the other following files:
https://github.com/awslabs/serverless-application-model/blob/master/examples/apps/splunk-cloudwatch-logs-processor/template.yaml
https://github.com/awslabs/serverless-application-model/blob/master/examples/apps/rekognition-python/template.yaml

Tried replacing `BucketNameParameter` with `!Ref Bucket1` but it ends up failing on `sam deploy` with a Circular dependency between resources: [s3getobject, Bucket1, s3getobjectBucketEventPermission, s3getobjectRole].

Could get the examples working quickly by going to the more permissive `AmazonS3FullAccess` for the Policies.

**Comment by ShreyaGangishetty** [comment]
Closing this issue as this is released in v1.14.0
