### ISSUE TITLE
 I am getting an error as "Circular dependency between resources: ".

### ISSUE THREAD

**Issue by Deliforce** [awslabs/serverless-application-model#646]
@sanathkr I am getting an error as "Circular dependency between resources: ". while using nested template for cloud formatioin deploy cli command
Even i removed transforms in nested stacks
Please help me with this
This is my template file
AWSTemplateFormatVersion: '2010-09-09'
Resources:
deliforceserver:
Type: AWS::CloudFormation::Stack
Properties:
TemplateURL: https://s3.ap-south-1.amazonaws.com/deliforcesck/d5b039ba137da028f009e478ecac3f1e.template
TimeoutInMinutes: '60'
Outputs:
StackRef:
Value: !Ref deliforceserver
OutputFromNestedStack:
Value: !GetAtt deliforceserver.Outputs.BucketName

**Comment by jlhood** [comment]
I don't see a circular dependency in the template snippet you pasted. It's possible you have one within the nested template. CloudFormation should tell you which resources are involved in the circular dependency as part of that error message which should help you debug.

Closing this issue since it's not specific to SAM, but a general CloudFormation question. If you're still stuck, I suggest posting your question to StackOverflow using the [amazon-cloudformation tag](https://stackoverflow.com/questions/tagged/amazon-cloudformation).
