### ISSUE TITLE
If you use the S3 event in SAM, then you don't see any trigger in the Lambda configuration panel.

### ISSUE THREAD

**Issue by wuxiongliu1** [awslabs/serverless-application-model#683]
But the Lambda function is executed when you drop a file in the S3 bucket.
![image](https://user-images.githubusercontent.com/13787479/37717693-5899ed6a-2d21-11e8-8675-5ff84f63fe0c.png)

_Originally posted by @bottemav in https://github.com/awslabs/serverless-application-model/issues/300#issuecomment-374969655_

**Comment by gartlady** [comment]
Currently experiencing this issue, any developments?

**Comment by keetonian** [comment]
Related to https://github.com/awslabs/serverless-application-model/issues/300

**Comment by brettstack** [comment]
My understanding is this is a Lambda console. If you have AWS Support, you can open a ticket through them. Otherwise, the AWS Lambda Forums might be a good place for this https://forums.aws.amazon.com/forum.jspa?forumID=186

**Comment by dmenin** [comment]
Hi @brettstack; 
I am experiencing the same issue. AWS support pointed me to this case:

"Its seem to be a know issue on the serverless application model. While researching on that I came across one open issue [1], describing the same problem. If possible, I’d suggest you to comment on the same issue [1] so that you can interact directly with the SAM developers who actually wrote the code for it or keep an eye on that issue [1] so that you’d get updates if there’s an fix made to this behavior"

why is the case closed? This is a genuine issue that can cause a lot of confusion.
Is this something that is being dealt with?
Thanks

**Comment by brettstack** [comment]
See my closure comment. It is thought that this is a Lambda Console Issue

**Comment by dmenin** [comment]
> See my closure comment. It is thought that this is a Lambda Console Issue

Hey @brettstack, AWS doesn't seem to think that as their support pointed me to this link. (The quoted statement I posted above is the reply I got after opening a case with Support).
Thanks for your help
