### ISSUE TITLE
Traffic shifting !Ref LatestVersionErrorMetricGreaterThanZeroAlarm

### ISSUE THREAD

**Issue by dave-graham** [awslabs/serverless-application-model#716]
The documentation for traffic shifting using code deploy is detailed here:

https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst#traffic-shifting-using-codedeploy

As part of the docs, there is a line of sam code:

- !Ref LatestVersionErrorMetricGreaterThanZeroAlarm

Now I may have implemented this wrong, but I've found that if there is an issue in production causing an alert, that I'm then prevented from deploying a fix.

The scenario that could cause this to happen, is a release is done at a time of low traffic, so no alerts fire. But at a higher traffic time users generate issues. Or an endpoint has a flaw in, but not one that registers during general use, however a malicious user sends malicious requests to the endpoint, causing errors, but you are then unable to deploy a fix, or release something that blocks the malicious requests.

I think the fix is to drop the line:

- !Ref LatestVersionErrorMetricGreaterThanZeroAlarm

Which is what we've done. I'm happy to update the docs via a pull request if you agree, however there maybe something I'm missing so wanted to open up for discussion.

**Comment by jlhood** [comment]
Thanks for bringing this up! We've dealt with this exact problem using this feature. I don't advocate for removing the alarm line in the same change as the fix, because in an emergency scenario, a code fix is too slow and risky. A rollback to a previous working version is a better mitigation strategy (preferably automated by a higher level CD orchestration system). Assuming you go with that approach, you can still run into the problem where the rollback fails because of the alarm state.

In this scenario, we go into the CodeDeploy console and edit the corresponding Deployment Group, selecting "ignore alarm configuration" under advanced settings. Then retry the rollback deployment and it should succeed. Then we uncheck "ignore alarm configuration" again.

If you agree with this approach, it'd be great if you could update the safe deployment doc page with this information.

**Comment by lestephane** [comment]
I find it a bit confusing that there are 2 alarms. In my understanding (from reading the reference alone), `AliasXAlarm` could triggers upon errors in `old` or `new` lambda code, `LatestXAlarm` only triggers upon errors in `new` lambda code. From reading this issue, I'm not so sure anymore.

Can someone explain the lambda version in which each alarm will find errors (`old` or `new` or `both`)?
I'd help me decide which alarm to keep if I only want to maintain one.

**Comment by jlhood** [comment]
@lestephane Your understanding of the two alarms defined in the docs is correct. `AliasXAlarm` is monitoring errors from old or new lambda code, `LatestXAlarm` is monitoring only errors on new lambda code. Reasons to have both alarms:

1. `LatestXAlarm` should be very sensitive, because any errors on the new lambda version could be treated as a faulty new version, triggering auto-rollback.
1. I've seen `AliasXAlarm` used to test for compatibility scenarios, i.e., where the new lambda version is writing data that the old lambda version cannot process. In these cases, the new lambda version has no errors, but the old version does.

**Comment by jlhood** [comment]
@dave-graham Would you be willing to update the docs based on this discussion?

**Comment by lestephane** [comment]
@dave-graham thanks for the heads-up, there also seems to be a typo in the safe deployment LatestXAlarm definition ( `MyLambdaFunction.Version.Version`)

![image](https://user-images.githubusercontent.com/5460884/50895089-be384580-140d-11e9-8b92-b09091da7b0e.png)
