### ISSUE TITLE
Multi Region deployment :: Region per resource in single SAM template

### ISSUE THREAD

**Issue by shailendrasharma83** [awslabs/serverless-application-model#824]
Hi Team,

For eg. We have a stack (SAM template which creates Lambda + API GW + SES templates) running in London region.. This will try to create all the resources in the region of execution.

As SES is not available in London region stack creation will fail. 

There should be a mechanism in SAM Templates to over ride the default execution region for a particular resource. if I continue my example. there should be a way to tell SAM to deploy the stack (API GW + Lambda) in London region whereas in case of SES templates do a cross region deployment in supported region say "eu-west-1".

Many Thanks.

**Comment by keetonian** [comment]
Are you saying that you'd like the ability to, in one template from one region, deploy resources to multiple different regions?

If you want to not deploy something in a certain region, CFN conditions can help with that, and SAM support for Conditions on `Serverless` resources is coming with our next release.

**Comment by shailendrasharma83** [comment]
answer to your question is .. Yes .. reason being .. few services are region bound and as the resources are functionally related to each other hence they can be part of the same template where as due unavailability of one of the service in that region that resource can be deployed in the appropriate region.

**Comment by jlhood** [comment]
@shailendrasharma83 SAM is an extension on top of CloudFormation which can only operate at the individual stack level. Since stacks are bound to a single region, SAM cannot provide the kind of cross-region functionality you're asking for.

CloudFormation does have a feature called [Stack Sets](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-concepts.html) which allow you to manage multiple stacks in different regions. You should be able to use Stack Sets along with region-specific conditions in your template (as @keetonian mentioned above) to achieve the desired behavior.

Closing this issue since it's not a feature SAM can provide.
