### ISSUE TITLE
How to set expiry on Cloudwatch logs?

### ISSUE THREAD

**Issue by johnc44** [awslabs/serverless-application-model#851]
How can I set the Expiry of the Cloudwatch logs generated for a function?

There's a PR here: https://github.com/awslabs/serverless-application-model/pull/460 but it's never been merged in.

Is there another way or is it something I need to script myself and run afterwards?

It would be really helpful if that PR could be merged.

**Comment by jlhood** [comment]
@johnc44 Here are the current options:

1. Explicitly define an `AWS::Logs::LogGroup` resource in your SAM template whose name matches Lambda's convention: /aws/lambda/<lambda function name>. Caveat: This will only work for new stacks, because if you try to add the log group resource to an existing stack where the Lambda function has already been invoked, the log group will already exist and CloudFormation will throw an error when it tries to create the log group.
1. Create a custom resource that updates the existing log group expiry time via an API call to [PutRetentionPolicy](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html).
1. Create a custom resource with the same properties as `AWS::Logs::LogGroup`, but only updates the log group to match the given properties if it already exists. This is a more generalized version of option 2.

The PR you referenced has not been merged because of the caveat called out in option 1. If we added this functionality, it would break existing stacks the next time they tried to update.

**Comment by johnc44** [comment]
Thanks for the info.  I had tried option 1 before, but it seemed to have some weird behaviour.  I can't remember exactly, but I think it worked the first time, then stopped afterwards and caused problems with updates.  Not entirely sure but I will give it another go.  If not, I will investigate the option options.

With the PR, can it not be altered to work in a backwards compatible way?  It's a really nice solution so it would be good if it could be made a part of SAM.

**Comment by adrian-skybaker** [comment]
To solve (1) you could make this behaviour opt-in.
