### ISSUE TITLE
RFC: Globals for nested applications

### ISSUE THREAD

**Issue by bikerp** [awslabs/serverless-application-model#863]
Hi, it would be nice if nested applications could inherit globals declared in root template.

**Comment by keetonian** [comment]
@bikerp Since SAM can't access or change the nested templates, this isn't currently possible. This would require giving SAM permission to read and change arbitrary templates in customer S3 buckets, which I think shouldn't be allowed and isn't currently possible. 

I think the best workaround is to have parameters for your global values and you can pass those parameters into the globals on your root template and pass them in as parameters to your child templates.
