### ISSUE TITLE
SAM + CORS + Cognito

### ISSUE THREAD

**Issue by leantorres73** [awslabs/serverless-application-model#957]
**Description:**

When I configure my API to use Cognito, it uses Cognito Authorizer in all of the methods. If I'm using CORS and Cognito, the OPTION method is still returning a 401.

**Observed result:**

401 in OPTIONS method

**Expected result:**

OPTIONS method shouldn't return unauthorized.

**Comment by jlhood** [comment]
@leantorres73 Thanks for reporting this issue. Can you provide us with a sample template that reproduces the problem you're experiencing and the steps to reproduce the 401 error so we can investigate further?

It's possible this issue could be fixed by #958, but we would need a sample template to confirm.

**Comment by leantorres73** [comment]
That's correct, I'm facing the same issues than 
https://github.com/awslabs/serverless-application-model/issues/717 and I'm pretty sure this will be fixed with the PR https://github.com/awslabs/serverless-application-model/pull/958.

**Comment by praneetap** [comment]
Released with v1.13.0
