### ISSUE TITLE
Feature Request: Lambda Log Group / Retention

### ISSUE THREAD

**Issue by marty-sullivan** [awslabs/serverless-application-model#972]
It would be great if the AWS::Serverless::Function supported the ability to define the corresponding AWS::Logs::LogGroup explicitly within the transformed template. While it's possible to create the LogGroup reference manually in a SAM template, this leads to a cluttered template and many extra resources that must be explicitly defined.

Considering the only parameters for the AWS::Logs::LogGroup are LogGroupName and RetentionInDays, it seems like it would not be very difficult to add a LogRetentionInDays Property to AWS::Serverless::Function that, when it is set, explicitly creates the AWS::Logs::LogGroup with that retention period within the transformed template.

**Comment by keetonian** [comment]
There was some discussion around this earlier in #257.

@jlhood explained why we shouldn't make this change in SAM: https://github.com/awslabs/serverless-application-model/issues/257#issuecomment-461896365

To summarize, this is a feature that would work if it were used on the first deployment of a stack, but could fail if it were added in later deployments because the log group would already exist. His suggestion of using a custom resource to set up the log groups is probably still the best path forward for this feature.
